Algoritmo "sei la"
Var
C:inteiro
N:inteiro
Inicio
Escreval("Algoritmo feito para contar de um número até tal número")
Escreval("Digite um número:")
Leia(C)
Escreval("Digite um segundo número:")
Leia(N)
Escreval("    ")
Enquanto (C>N) Faca
         Escreval(C)
         C <- C-1
FimEnquanto
Enquanto (N>=C) Faca
         Escreval(C)
         C <- C+1
FimEnquanto
Enquanto (C=N) Faca
         Escreval(C)
FimEnquanto
Fimalgoritmo
